### ISSUE TITLE
require.js:117 Require cycle: node_modules/react-native-payments/lib/js/PaymentRequest.js -> node_modules/react-native-payments/lib/js/PaymentRequestUpdateEvent.js -> node_modules/react-native-payments/lib/js/PaymentRequest.js  Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

### ISSUE THREAD

**Issue by Sandeep200995** [naoufal/react-native-payments#226]
After modifying the podspecs file in react-native payments , reinstalling cocoa pods and relinking
I got this error on calling any methods of react-native payment .

**Comment by JollyGolf** [comment]
go to ‘node_modules/react-native-payments’ and Open the ReactNativePayments.podspec file. At line 3 replace to "package = JSON.parse(File.read(File.join(dir, "package.json")))"

**Comment by Sandeep200995** [comment]
![Screenshot 2020-04-13 at 9 58 05 PM](https://user-images.githubusercontent.com/41103211/79138273-e2818f80-7dd1-11ea-99dd-63d2f090e8d8.png)

**Comment by Sandeep200995** [comment]
not worked

**Comment by nabilfreeman** [comment]
Hey @Sandeep200995, we have fixed the podspec and will be releasing v0.8 which supports autolinking in a couple of days' time. This should resolve your issue. Check back soon!

**Comment by tycali17** [comment]
> Hey @Sandeep200995, we have fixed the podspec and will be releasing v0.8 which supports autolinking in a couple of days' time. This should resolve your issue. Check back soon!

Hello, it seems the cycle is still present. I changed the line 3 as instructed by JollyGolf, but the 'giturl' line is different now. It's now: s.source           = { :git => pkg["repository"]["url"] }       and is on a different line than specified. I hope there is a fix to this. Here is the present podspec, that triggers the cycle
`require 'json'
# pkg = JSON.parse(File.read("package.json"))
pkg = JSON.parse(File.read(File.join(dir, "package.json")))

Pod::Spec.new do |s|
  s.name             = pkg["name"]
  s.version          = pkg["version"]
  s.summary          = pkg["description"]
  s.requires_arc     = true
  s.license          = pkg["license"]
  s.homepage         = pkg["homepage"]
  s.author           = pkg["author"]
  s.source           = { :git => pkg["repository"]["url"] }
  s.source_files     = 'ios/**/*.{h,m}'
  s.platform         = :ios, "8.0"
  s.requires_arc     = true

  s.dependency 'React'
  s.dependency 'Stripe'
  s.dependency 'Braintree'
end
`

I hope we can fix this, or is the app able to proceed even with the cycle?

**Comment by Chhinvanchhai** [comment]
I still have the same problem on 30/01/2020

**Comment by hassanAwanAlvi** [comment]
facing the same issue!!! October 21, 2022!!!
